// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mraavqiezsuftfjhuxbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYWF2cWllenN1ZnRmamh1eGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzk4MzMsImV4cCI6MjA2MDY1NTgzM30.ydkpuivE4aQzv7ekUwraVb9OyijKpOwlLI0_GTWi1Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);